package pandemic.aider.client;

final public class CONSTANTS {
	
	public static final String LOWERCASE_ALPHA = "abcdefghijklmnopqrstuvwxyz";
	public static final String UPPERCASE_ALPHA = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
	public static final String NUMBERS = "0123456789";
	public static final String ALLOWED_CHARS = "_.";
	
	public static final String ALLOWED_USERNAME_CHARS = LOWERCASE_ALPHA + NUMBERS + ALLOWED_CHARS;
	public static final String COMBINED_CHARS = LOWERCASE_ALPHA + UPPERCASE_ALPHA + NUMBERS + ALLOWED_CHARS;
	public static final String PEPPER_PASSWORD = "$2a$10$yubOW.BNOsuNXHfzo1M1xO";
	
	//	public static final String[] JAVA_FX_ARGUMENTS=[" --module-path \"C:\\Users\tejas\\Downloads\\Json\\java fx lib" --add-modules javafx.controls,javafx.fxml "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\idea_rt.jar=8581:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\NHCE\4th-Sem-College\Mini-Project\Code\FrontEnd-PA v2\out\production\FrontEnd-PA v2;C:\Users\tejas\Downloads\Json\poi-3.17.jar;C:\Users\tejas\Downloads\Json\gson-2.8.7.jar;C:\Users\tejas\Downloads\Json\json-20210307.jar;C:\Users\tejas\Downloads\Json\javafx-base-16.jar;C:\Users\tejas\Downloads\Json\javafx-fxml-16.jar;C:\Users\tejas\Downloads\Json\jfoenix-9.0.10.jar;C:\Users\tejas\Downloads\Json\poi-ooxml-3.17.jar;C:\Users\tejas\Downloads\Json\xmlbeans-2.6.0.jar;C:\Users\tejas\Downloads\Json\fontawesomefx-8.9.jar;C:\Users\tejas\Downloads\Json\fontawesomefx-8.91.jar;C:\Users\tejas\Downloads\Json\javafx-base-16-win.jar;C:\Users\tejas\Downloads\Json\javafx-controls-16.jar;C:\Users\tejas\Downloads\Json\javafx-fxml-16-win.jar;C:\Users\tejas\Downloads\Json\javafx-graphics-16.jar;C:\Users\tejas\Downloads\Json\bcrypt-0.9.0-javadoc.jar;C:\Users\tejas\Downloads\Json\bcrypt-0.9.0-optimized.jar;C:\Users\tejas\Downloads\Json\javafx-controls-16-win.jar;C:\Users\tejas\Downloads\Json\javafx-graphics-16-win.jar;C:\Users\tejas\Downloads\Json\poi-ooxml-schemas-3.17.jar;C:\Users\tejas\Downloads\Json\apache-commons-codec-1.4.jar;C:\Users\tejas\Downloads\Json\commons-collections4-4.1.jar;C:\Users\tejas\Downloads\Json\apache-commons-codec-1.4.jar.zip;C:\Users\tejas\Downloads\Json\spring-security-crypto-5.5.0.jar;C:\Additional Program Files\Java\javafx-sdk-11.0.2\lib\src.zip;C:\Additional Program Files\Java\javafx-sdk-11.0.2\lib\javafx-swt.jar;C:\Additional Program Files\Java\javafx-sdk-11.0.2\lib\javafx.web.jar;C:\Additional Program Files\Java\javafx-sdk-11.0.2\lib\javafx.base.jar;C:\Additional Program Files\Java\javafx-sdk-11.0.2\lib\javafx.fxml.jar;C:\Additional Program Files\Java\javafx-sdk-11.0.2\lib\javafx.media.jar;C:\Additional Program Files\Java\javafx-sdk-11.0.2\lib\javafx.swing.jar;C:\Additional Program Files\Java\javafx-sdk-11.0.2\lib\javafx.controls.jar;C:\Additional Program Files\Java\javafx-sdk-11.0.2\lib\javafx.graphics.jar;C:\NHCE\4th-Sem-College\Mini-Project\Code\FrontEnd-PA v2\lib\annotations-20.1.0.jar" pandemic.aider.client.ui.main.Main
//			"]
	public static final String[] JAVA_FX_ARGUMENTS = {"--module-path", "\"C:\\Users\\tejas\\Downloads\\Json\\java fx lib\"", "--add-modules", "javafx.controls,javafx.fxml"};
	//--module-path "C:\Users\tejas\Downloads\Json\java fx lib" --add-modules javafx.controls,javafx.fxml                 "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\idea_rt.jar=1225:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\NHCE\4th-Sem-College\Mini-Project\Code\FrontEnd-PA v2\out\production\FrontEnd-PA                              v2;C:\Users\tejas\Downloads\Json\poi-3.17.jar;C:\Users\tejas\Downloads\Json\gson-2.8.7.jar;C:\Users\tejas\Downloads\Json\json-20210307.jar;C:\Users\tejas\Downloads\Json\javafx-base-16.jar;C:\Users\tejas\Downloads\Json\javafx-fxml-16.jar;C:\Users\tejas\Downloads\Json\jfoenix-9.0.10.jar;C:\Users\tejas\Downloads\Json\poi-ooxml-3.17.jar;C:\Users\tejas\Downloads\Json\xmlbeans-2.6.0.jar;C:\Users\tejas\Downloads\Json\fontawesomefx-8.9.jar;C:\Users\tejas\Downloads\Json\fontawesomefx-8.91.jar;C:\Users\tejas\Downloads\Json\javafx-base-16-win.jar;C:\Users\tejas\Downloads\Json\javafx-controls-16.jar;C:\Users\tejas\Downloads\Json\javafx-fxml-16-win.jar;C:\Users\tejas\Downloads\Json\javafx-graphics-16.jar;C:\Users\tejas\Downloads\Json\bcrypt-0.9.0-javadoc.jar;C:\Users\tejas\Downloads\Json\bcrypt-0.9.0-optimized.jar;C:\Users\tejas\Downloads\Json\javafx-controls-16-win.jar;C:\Users\tejas\Downloads\Json\javafx-graphics-16-win.jar;C:\Users\tejas\Downloads\Json\poi-ooxml-schemas-3.17.jar;C:\Users\tejas\Downloads\Json\apache-commons-codec-1.4.jar;C:\Users\tejas\Downloads\Json\commons-collections4-4.1.jar;C:\Users\tejas\Downloads\Json\apache-commons-codec-1.4.jar.zip;C:\Users\tejas\Downloads\Json\spring-security-crypto-5.5.0.jar;C:\Additional Program Files\Java\javafx-sdk-11.0.2\lib\src.zip;C:\Additional Program Files\Java\javafx-sdk-11.0.2\lib\javafx-swt.jar;C:\Additional Program Files\Java\javafx-sdk-11.0.2\lib\javafx.web.jar;C:\Additional Program Files\Java\javafx-sdk-11.0.2\lib\javafx.base.jar;C:\Additional Program Files\Java\javafx-sdk-11.0.2\lib\javafx.fxml.jar;C:\Additional Program Files\Java\javafx-sdk-11.0.2\lib\javafx.media.jar;C:\Additional Program Files\Java\javafx-sdk-11.0.2\lib\javafx.swing.jar;C:\Additional Program Files\Java\javafx-sdk-11.0.2\lib\javafx.controls.jar;C:\Additional Program Files\Java\javafx-sdk-11.0.2\lib\javafx.graphics.jar;C:\NHCE\4th-Sem-College\Mini-Project\Code\FrontEnd-PA v2\lib\annotations-20.1.0.jar" pandemic.aider.client.ui.main.Main
	
	public static final String[] JAVA_FX_ARGUMENTS_NEW = {"--module-path", "\"C:\\Users\\tejas\\Downloads\\Json\\java fx lib\"", "--add-modules", "javafx.controls,javafx.fxml", "\"-javaagent:C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2021.1\\lib\\idea_rt.jar=1225:C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2021.1\\bin\"", "-Dfile.encoding=UTF-8", "-classpath", "\"C:\\NHCE\\4th-Sem-College\\Mini-Project\\Code\\FrontEnd-PA v2\\out\\production\\FrontEnd-PA v2;C:\\Users\\tejas\\Downloads\\Json\\poi-3.17.jar;C:\\Users\\tejas\\Downloads\\Json\\gson-2.8.7.jar;C:\\Users\\tejas\\Downloads\\Json\\json-20210307.jar;C:\\Users\\tejas\\Downloads\\Json\\javafx-base-16.jar;C:\\Users\\tejas\\Downloads\\Json\\javafx-fxml-16.jar;C:\\Users\\tejas\\Downloads\\Json\\jfoenix-9.0.10.jar;C:\\Users\\tejas\\Downloads\\Json\\poi-ooxml-3.17.jar;C:\\Users\\tejas\\Downloads\\Json\\xmlbeans-2.6.0.jar;C:\\Users\\tejas\\Downloads\\Json\\fontawesomefx-8.9.jar;C:\\Users\\tejas\\Downloads\\Json\\fontawesomefx-8.91.jar;C:\\Users\\tejas\\Downloads\\Json\\javafx-base-16-win.jar;C:\\Users\\tejas\\Downloads\\Json\\javafx-controls-16.jar;C:\\Users\\tejas\\Downloads\\Json\\javafx-fxml-16-win.jar;C:\\Users\\tejas\\Downloads\\Json\\javafx-graphics-16.jar;C:\\Users\\tejas\\Downloads\\Json\\bcrypt-0.9.0-javadoc.jar;C:\\Users\\tejas\\Downloads\\Json\\bcrypt-0.9.0-optimized.jar;C:\\Users\\tejas\\Downloads\\Json\\javafx-controls-16-win.jar;C:\\Users\\tejas\\Downloads\\Json\\javafx-graphics-16-win.jar;C:\\Users\\tejas\\Downloads\\Json\\poi-ooxml-schemas-3.17.jar;C:\\Users\\tejas\\Downloads\\Json\\apache-commons-codec-1.4.jar;C:\\Users\\tejas\\Downloads\\Json\\commons-collections4-4.1.jar;C:\\Users\\tejas\\Downloads\\Json\\apache-commons-codec-1.4.jar.zip;C:\\Users\\tejas\\Downloads\\Json\\spring-security-crypto-5.5.0.jar;C:\\Additional Program Files\\Java\\javafx-sdk-11.0.2\\lib\\src.zip;C:\\Additional Program Files\\Java\\javafx-sdk-11.0.2\\lib\\javafx-swt.jar;C:\\Additional Program Files\\Java\\javafx-sdk-11.0.2\\lib\\javafx.web.jar;C:\\Additional Program Files\\Java\\javafx-sdk-11.0.2\\lib\\javafx.base.jar;C:\\Additional Program Files\\Java\\javafx-sdk-11.0.2\\lib\\javafx.fxml.jar;C:\\Additional Program Files\\Java\\javafx-sdk-11.0.2\\lib\\javafx.media.jar;C:\\Additional Program Files\\Java\\javafx-sdk-11.0.2\\lib\\javafx.swing.jar;C:\\Additional Program Files\\Java\\javafx-sdk-11.0.2\\lib\\javafx.controls.jar;C:\\Additional Program Files\\Java\\javafx-sdk-11.0.2\\lib\\javafx.graphics.jar;C:\\NHCE\\4th-Sem-College\\Mini-Project\\Code\\FrontEnd-PA v2\\lib\\annotations-20.1.0.jar\"" ,"pandemic.aider.client.ui.main.Main"};
}